kit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('solicitacao/', include('solicitacao.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

solicitacao/urls.py
from django.urls import path
from solicitacao.views import home_view, solicitar, listar, finalizar, informacoes

urlpatterns = [
    #path('my_view/', my_view, name="qr_code"),
    path('home/', home_view, name='home'),
    path('solicitar/', solicitar, name="solicitar"),
    path('listar/', listar, name="listar"),
    path('finalizar/<id>', finalizar, name="finalizar"),
    path('informacoes/<id>', informacoes, name="informacoes"),
    
]

solicitacao/models.py
from xml.parsers.expat import model
from django.db import models
import qrcode
from io import BytesIO
from django.core.files import File
from PIL import Image, ImageDraw

class Funcionario(models.Model):
    id = models.AutoField(primary_key=True)
    nome= models.CharField(max_length=100, verbose_name="Nome do cracha")
    matricula = models.IntegerField(verbose_name="matricula da empresa")
    setor = models.CharField(max_length=50, verbose_name="Setor")


class Equipamento(models.Model):
    id = models.AutoField(primary_key=True)
    descricao = models.CharField(max_length=150, verbose_name="Nome do equipamento")
    status = models.BooleanField(default=True)
    
    def __str__(self):
        return f"{self.descricao}"


class Kit(models.Model):
    STATUS_KIT = [
        ("EM_USO", "Em uso"),
        ("INDISPONIVEL", "Indisponivel"),
        ("DISPONIVEL", "Disponivel"),
    ]
    
    id = models.AutoField(primary_key=True)
    descricao = models.CharField(max_length=150, verbose_name="Nome do kit")
    image = models.ImageField(upload_to="img/%Y/%m/%d", null=False, blank=False)
    qr_code = models.ImageField(upload_to="qr_codes", blank=True)
    equipamentos = models.ForeignKey(Equipamento, on_delete=models.PROTECT, verbose_name="Equipamento")
    status = models.CharField(verbose_name="Status", max_length=12, choices=STATUS_KIT, default="DISPONIVEL")
    url = models.CharField(max_length=250, verbose_name="url")

    def __str__(self):
        return f"{self.descricao}"

    def save(self, *args, **kwargs):
        qrcode_img = qrcode.make([self.descricao, self.equipamentos, self.image.url, self.url])
        canvas = Image.new('RGB', (470,470), 'white')
        draw = ImageDraw.Draw(canvas)
        canvas.paste(qrcode_img)
        fname = f'qrcode-{self.url}'
        buffer = BytesIO()
        canvas.save(buffer, 'PNG')
        self.qr_code.save(fname, File(buffer), save=False)
        canvas.close()
        super().save(*args, **kwargs)


class Solicitacao(models.Model):
    STATUS_SOLICITACAO = [
        ("SOLICITADO", "Solicitado"),
        ("FINALIZADO", "Finalizado"),
    ]
    
    id = models.AutoField(primary_key=True)
    kit = models.ForeignKey(Kit, on_delete=models.PROTECT, verbose_name="Kit Solicitado")
    #kit  = models.CharField(max_length=150, verbose_name="Nome do kit")
    #equipamento = models.CharField(max_length=150, verbose_name="Equipamentos que compoe o kit")
    data = models.DateField(auto_now=False, blank=True, null=True)
    hora = models.TimeField(auto_now=False, blank=True, null=True)
    matricula = models.IntegerField(verbose_name="Matricula do solicitante")   
    status = models.CharField(verbose_name="Solicitação", max_length=12, choices=STATUS_SOLICITACAO, default="SOLICITADO")
    hora_termino = models.TimeField(auto_now=False, blank=True, null=True)
    observacao = models.TextField(verbose_name="Observação", blank=True, null=True)

    def __str__(self):
        return f"{self.kit}"

solicitacao/forms.py
from django import forms
from solicitacao.models import Solicitacao

class SolicitacaoForm(forms.ModelForm):
    class Meta:
        model = Solicitacao
        fields = [
            "kit", "matricula","observacao"
        ]

solicitacao/views.py
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseNotAllowed
from solicitacao.models import Kit, Solicitacao
from solicitacao.forms import SolicitacaoForm
from django.core.paginator import Paginator

from qr_code.qrcode.utils import MeCard, VCard, EpcData, WifiConfig, Coordinates, QRCodeOptions

def home_view(request):
    name = "Bem vindo"

    obj = Kit.objects.all()
    vcard_contact = VCard(
        name='',
        url='http://192.168.147.99:8000/solicitacao/solicitar/',
            )

    context = {
        'name': name,
        'vcard_contact': vcard_contact,
        'obj' : obj,
    }

    return render(request, 'solicitacao/home.html', context)



def solicitar(request):
    
    form = SolicitacaoForm()
    obj = Kit.objects.all()

    if request.method == "POST":
        form = SolicitacaoForm(request.POST, request.FILES)
        
        if form.is_valid():
            print(form)
            solicita = form.save(commit=False)
            solicita.data = timezone.now()
            solicita.hora = timezone.localtime(timezone.now())
            obj.status = "EM_USO"
            solicita.save()
            messages.success(request, "Solicitacao realizado com sucesso")
            
            return redirect('/solicitacao/listar')

    context = {
        "nome_pagina": 'Cadastrar Solicitacao',
        'form': form,
        'obj':obj
    }

    return render(request, 'solicitacao/solicitar.html', context)


def listar(request):
    solicitacao = Solicitacao.objects.all().order_by('-data')
    paginacao = Paginator(solicitacao, 10)
    numero_pagina = request.GET.get('page')
    
    try:
        pag_solicita = paginacao.get_page(numero_pagina)  # returns the desired page object
    except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        pag_solicita = paginacao.page(1)
    except EmptyPage:
        # if page is empty then return last page
        pag_solicita = paginacao.page(paginacao.num_pages)

    context = {
        "nome_pagina": 'Cadastrar Solicitacao',
        'solicitacao': solicitacao,
        "pag_solicita": pag_solicita
    }

    return render(request, 'solicitacao/listar.html', context)


def informacoes(request, id):

    solicitacao = get_object_or_404(Solicitacao, id = id)

    form = SolicitacaoForm(instance=solicitacao)

    context = {
        "nome_pagina": "Infomações do solicitacao",
        "solicitacao": solicitacao,
        "form": form,
    }

    return render(request, "solicitacao/informacoes.html", context)


def finalizar(request, id):

    if request.method == "POST":

        solicitacao = get_object_or_404(Solicitacao, id=id)
        solicitacao.status = "FINALIZADO"
        solicitacao.kit.status = "DISPONIVEL"
        solicitacao.hora_termino = timezone.localtime(timezone.now())

        solicitacao.save()

        messages.success(
            request,
            "solicitacao finalizada com sucesso"
        )

        return redirect("/solicitacao/listar")

    else:
        return HttpResponseNotAllowed(
            ["POST"],
            "Método não permitido"
        )

templates/solicitacao/base.html
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Simple Forms{% endblock %}</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <style type="text/css">
    main { min-height: 400px; }
    footer .container a { margin-right: 10px; }
  </style>
</head>
<body>
  <header>
    <div class="container">
      <h1 class="page-header">Sistema de Solicitação</h1>
    </div>
  </header>
  <main>
    <div class="container">
        {% block conteudo %} {% endblock %}
        {% block content %} {% endblock %}
        {% block informacoes %} {% endblock %}
    </div>
  </main>
  <footer>
    <div class="container">
      <hr>
      <a href="https://www.gruporedeamazonica.com.br/" title="gruporedeamazonica" target="_blank">Gram</a>
      <a href="https://twitter.com/RedeAmazonica?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor" title="gruporedeamazonica" target="_blank"><i class="fa-brands fa-twitter"></i></a>
      <a href="https://instagram.com/redeamazonicaoficial?igshid=NmZiMzY2Mjc=" title="gruporedeamazonica" target="_blank"><i class="fa-brands fa-instagram"></i></a>
    </div>
  </footer>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>

templates/solicitacao/home.html
{% load static %}
{% load qr_code %}
<!doctype html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

  
    <title>QrCode</title>
  </head>
  <body>
    <div class="ui container">
    <h3>Kit</h3>
    {% qr_for_vcard vcard=vcard_contact size='S' %}   
    </div>

  </body>
</html>

templates/solicitacao/informacoes.html
{% extends "solicitacao/base.html" %}
{% block informacoes %}
{% load widget_tweaks %}
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Kit</th>
        <th>Status Kit</th>
        <th>Matricula</th>
        <th>Equipamentos</th>
        <th>Status</th>
        <th>Data Solicitacao</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      
        <tr>
          <td>{{ solicitacao.id }}</td>
          <td>{{ solicitacao.kit }}</td>
          <td>{{ solicitacao.kit.status }}</td>
          <td>{{ solicitacao.matricula }}</td>
          <td>{{ solicitacao.kit.equipamentos }}</td>
          <td>{{ solicitacao.status }}</td>
          <td>{{ solicitacao.data }}</td>
          <td>
            {% if solicitacao.status == "SOLICITADO" %}
                <a href="#" class="btn btn-success btn-icon-split btn-sm" data-toggle="modal" data-target="#modal">
                    <span class="text">Finalizar Solicitacao</span>

                    <span class="icon text-white-50">
                        <i class="fas fa-door-open"></i>
                    </span>
                </a>
            {% endif %}
          </td>
        </tr>
     
    </tbody>
  </table>
  <div class="form-group">
    <a href="{% url 'listar' %}" class="btn btn-default">Cancel</a>
  </div>


  <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Finalizar Solicitacao</h5>
                            
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                        <div class="modal-body">
                            <h5 class="mb-3">
                                Realmente deseja encerrar a solicitacao?
                            </h5>
        
                            <form method="post" action="{% url 'finalizar' id=solicitacao.id %}">
                                {% csrf_token %}

        
                                 <div class="form-group">
                                    <label for="id_observacao" class="col-form-label">Deseja escrever alguma observação?</label>
                                    {% render_field form.observacao placeholder="Deseja escrver alguma observação?" class="form-control" %}
                                </div>
        
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                    <button type="submit" class="btn btn-primary">Finalizar solicitacao</button>
                                </div>
                            </form>
                        </div>
                </div>
            </div>
        </div>

{% endblock %}

templates/solicitacao/listar.html
{% extends "solicitacao/base.html" %}
{% block content %}

  <h2>
    Solicitações
    <a href="{% url 'solicitar' %}" class="btn btn-primary pull-right">
      <span class="glyphicon glyphicon-plus"></span> Add Solicitação
    </a>
  </h2>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Kit</th>
        <th>Status Kit</th>
        <th>Matricula</th>
        <th>Equipamentos</th>
        <th>Status</th>
        <th>Data Solicitacao</th>
        <th>Hora Solicitacao</th>
        <th>Observação</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
    
      {% for solicitacoes in pag_solicita.object_list %}
        <tr>
          <td>{{ solicitacoes.id }}</td>
          <td>{{ solicitacoes.kit }}</td>
          <td>{{ solicitacoes.kit.status }}</td>
          <td>{{ solicitacoes.matricula }}</td>
          <td>{{ solicitacoes.kit.equipamentos }}</td>
          <td>{{ solicitacoes.status }}</td>
          <td>{{ solicitacoes.data }}</td>
          <td>{{ solicitacoes.hora }}</td>
          <td>{{ solicitacoes.observacao }}</td>
          <td>
            <a href="{% url 'informacoes' id=solicitacoes.id %}">
            <i class="fas fa-info-circle"></i></a>
        </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="6" class="text-center">Sem resultado</td>
        </tr>
        
      {% endfor %}
  </tbody>
</table>
<center>
    {% if pag_solicita.has_previous %}
        <a href="?page={{pag_solicita.previous_page_number}}"><i class="fa-solid fa-circle-chevron-left"></i></i></a>
    {% endif %}
    <span>{{pag_solicita.number}}</span>
    
    {% if pag_solicita.has_next %} {# whether the next page exists #}
        <a href="?page={{pag_solicita.next_page_number}}"><i class="fa-solid fa-circle-chevron-right"></i></a>
    {% endif %}
</center>
{% endblock %}

templates/solicitacao/solicitar.html
{% extends "solicitacao/base.html" %}
{% load widget_tweaks %}
{% block conteudo %}
<div class="container">

    <div class="card shadow mb-4">
        <div class="card-body">
            <h4 class="mb-3 text-primary">
                Formulário para cadastrar Solicitacao
            </h4>
            <form method="post">
                <div class="form-row">
                    {% csrf_token %}

                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}

                    {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field|add_class:'form-control' }}
                        {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% endfor %}

                <div class="form-group">
                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-ok"></span> Save
                </button>
                <a href="{% url 'listar' %}" class="btn btn-default">Cancel</a>
                </div>

                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}